using System;
using System.Windows;
using WinCraft.Compatibility;
using WinCraft.Infrastructure;
using Windows.Win32;
using Windows.Win32.Foundation;
using Windows.Win32.Graphics.Gdi;
using Windows.Win32.UI.Controls;
using Windows.Win32.UI.Shell;
using Windows.Win32.UI.WindowsAndMessaging;

namespace WinCraft.UI
{
    public abstract partial class WindowBase
    {
        private IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            switch ((uint)msg)
            {
                case PInvoke.WM_ERASEBKGND:
                    return HandleEraseBkgnd(wParam, ref handled);

                case PInvoke.WM_DWMCOMPOSITIONCHANGED:
                    HandleDwmCompositionChanged();
                    return IntPtr.Zero;

                case PInvoke.WM_ENTERSIZEMOVE:
                    // Startup centering completes at Loaded. Once the user starts
                    // a native move/size loop, preserving
                    // the dragged rectangle takes precedence over centering.
                    EndStartupPositionCorrection();

                    // Legacy Acrylic (SetWindowCompositionAttribute) has a
                    // drag-lag bug; temporarily switch to lightweight Blur.
                    DwmBackdrop.BeginDragFallback(_hwnd, ToDwmBackdropType(BackdropType));
                    SetValue(SizeMoveStatePropertyKey, _pendingSizeMove);
                    return IntPtr.Zero;

                case PInvoke.WM_EXITSIZEMOVE:
                    DwmBackdrop.EndDragFallback(
                        _hwnd,
                        ToDwmBackdropType(BackdropType),
                        ToAccentColor(AcrylicGradientColor));
                    SetValue(SizeMoveStatePropertyKey, SizeMoveState.None);
                    return IntPtr.Zero;

                case PInvoke.WM_HELP:
                    return HandleHelp(lParam, ref handled);

                case PInvoke.WM_KEYDOWN:
                    if (_isHelpMode && (int)wParam == 0x1B /* VK_ESCAPE */)
                    {
                        ExitHelpMode();
                        handled = true;
                        return IntPtr.Zero;
                    }
                    break;

                case PInvoke.WM_LBUTTONDOWN:
                    if (_isHelpMode)
                    {
                        ExitHelpMode();

                        var pt = new System.Drawing.Point(
                            Windowsx.GetXLParam(lParam), Windowsx.GetYLParam(lParam));
                        if (PInvoke.ClientToScreen((HWND)hwnd, ref pt))
                            DispatchHelpRequestAt(pt.X, pt.Y);

                        handled = true;
                        return IntPtr.Zero;
                    }
                    break;

                case PInvoke.WM_SYSCOMMAND:
                    // DefWindowProc enters the modal loop from SC_MOVE / SC_SIZE;
                    // remember which one so SizeMoveState can tell them apart.
                    uint systemCommand = Windowsx.GetSystemCommand(wParam);
                    switch (systemCommand)
                    {
                        case PInvoke.SC_MOVE:
                            _pendingSizeMove = SizeMoveState.Moving;
                            break;
                        case PInvoke.SC_SIZE:
                            _pendingSizeMove = SizeMoveState.Resizing;
                            break;
                        case PInvoke.SC_CONTEXTHELP:
                            // WPF swallows the native help button's system
                            // command; hand-roll the help loop instead.
                            EnterHelpMode();
                            handled = true;
                            return IntPtr.Zero;
                    }

                    // Close capability off: swallow SC_CLOSE from the button,
                    // system menu, and Alt+F4; programmatic Close() unaffected.
                    if (!ShowClose && systemCommand == PInvoke.SC_CLOSE)
                    {
                        handled = true;
                        return IntPtr.Zero;
                    }
                    break;
            }

            return OnWndProc(msg, wParam, lParam, ref handled);
        }

        private SizeMoveState _pendingSizeMove = SizeMoveState.Moving;

        // ── HELP ──

        // Both help buttons end in the OS help mode, which reports the
        // subsequent click here with screen coordinates.
        private IntPtr HandleHelp(IntPtr lParam, ref bool handled)
        {
            // Ignore the WM_HELP generated by the unhandled F1 key press
            // following the command-binding dispatch.  Consume the flag
            // unconditionally — stale true (e.g. from test isolation) only
            // skips the very next WM_HELP.
            bool squelch = _helpSquelch;
            _helpSquelch = false;
            if (squelch)
            {
                handled = true;
                return (IntPtr)1;
            }

            // Prevent re-entrancy: the help-mode loop hasn't ended yet while
            // a handler opens a modal dialog, and a click on the dialog can
            // generate another WM_HELP before the first returns.
            if (_isInHelpDispatch) return IntPtr.Zero;
            _isInHelpDispatch = true;
            try
            {
                var info = MarshalCompat.PtrToStructure<HELPINFO>(lParam);
                DispatchHelpRequestAt(info.MousePos.X, info.MousePos.Y);
                handled = true;
                return (IntPtr)1;
            }
            finally
            {
                _isInHelpDispatch = false;
            }
        }

        private bool _isInHelpDispatch;

        /// <summary>Subclass hook for every message the shared pipeline leaves unhandled.</summary>
        private protected virtual IntPtr OnWndProc(int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
        {
            return IntPtr.Zero;
        }

        // ── ERASEBKGND ──

        private IntPtr HandleEraseBkgnd(IntPtr wParam, ref bool handled)
        {
            if (TryGetEraseBackgroundColor(out System.Windows.Media.Color backgroundColor))
            {
                PInvoke.GetClientRect((HWND)_hwnd, out RECT cr);
                var br = PInvoke.CreateSolidBrush(new COLORREF(ToColorRef(backgroundColor)));
                if (!br.IsNull)
                {
                    unsafe
                    {
                        PInvoke.FillRect((HDC)wParam, &cr, br);
                        PInvoke.DeleteObject(br);
                    }
                }
                handled = true;
                return (IntPtr)1;
            }
            return IntPtr.Zero;
        }

        // ── Window button capabilities ──

        private protected bool MinimizeBoxVisible => ShowMinimize && ResizeMode != ResizeMode.NoResize;
        private protected bool MaximizeBoxVisible => ShowMaximize && IsResizable(ResizeMode);

        /// <summary>
        /// Sets WS_MINIMIZEBOX / WS_MAXIMIZEBOX from ResizeMode and the
        /// ShowMinimize / ShowMaximize toggles so taskbar commands, Win+Up/Down,
        /// Aero Snap, and Snap Layout follow them.
        /// </summary>
        private protected virtual void ApplyWindowButtonStyle()
        {
            if (_hwnd == IntPtr.Zero) return;

            int style = PInvoke.GetWindowLongPtr(
                (HWND)_hwnd, WINDOW_LONG_PTR_INDEX.GWL_STYLE).ToInt32();
            int newStyle = ComputeWindowStyle(style, MinimizeBoxVisible, MaximizeBoxVisible);
            if (newStyle != style)
                PInvoke.SetWindowLongPtr(
                    (HWND)_hwnd, WINDOW_LONG_PTR_INDEX.GWL_STYLE, new IntPtr(newStyle));
        }

        internal static int ComputeWindowStyle(int style, bool minimizeBox, bool maximizeBox)
        {
            style = minimizeBox
                ? style | (int)WINDOW_STYLE.WS_MINIMIZEBOX
                : style & ~(int)WINDOW_STYLE.WS_MINIMIZEBOX;
            return maximizeBox
                ? style | (int)WINDOW_STYLE.WS_MAXIMIZEBOX
                : style & ~(int)WINDOW_STYLE.WS_MAXIMIZEBOX;
        }

        // ── DPI ──

        private protected double GetDpiScale()
        {
            var s = PresentationSource.FromVisual(this);
            return s?.CompositionTarget?.TransformToDevice.M11 ?? 1.0;
        }

        // ── DWMCOMPOSITIONCHANGED ──

        private void HandleDwmCompositionChanged()
        {
            _isDwmEnabled = DwmCorner.IsDwmAvailable();
            UpdateBackdropSurface(_isDwmEnabled && BackdropType != WindowBackdropType.None);
            ApplyDwmFrame();
            ApplyDwmEffects();
            RefreshNonClientFrame();
        }

        // ── DWM Frame ──

        private static MARGINS GetFrameMargins(bool fullGlass)
        {
            return fullGlass
                ? new MARGINS
                {
                    cxLeftWidth = -1,
                    cxRightWidth = -1,
                    cyTopHeight = -1,
                    cyBottomHeight = -1,
                }
                : new MARGINS { cyTopHeight = 1 };
        }

        private protected virtual void ApplyDwmFrame()
        {
            if (!_isDwmEnabled) return;

            DwmCorner.EnableNcRendering(_hwnd);
            var margins = WindowsVersion.IsBelow(WindowsRelease.Win8)
                ? default
                : GetFrameMargins(
                    WindowsVersion.IsAtLeast(WindowsRelease.Win11_21H2)
                    && BackdropType != WindowBackdropType.None);
            PInvoke.DwmExtendFrameIntoClientArea((HWND)_hwnd, in margins);
        }

        private protected void RefreshNonClientFrame()
        {
            PInvoke.SetWindowPos((HWND)_hwnd, HWND.Null, 0, 0, 0, 0,
                SET_WINDOW_POS_FLAGS.SWP_FRAMECHANGED
                | SET_WINDOW_POS_FLAGS.SWP_NOMOVE
                | SET_WINDOW_POS_FLAGS.SWP_NOSIZE
                | SET_WINDOW_POS_FLAGS.SWP_NOZORDER
                | SET_WINDOW_POS_FLAGS.SWP_NOACTIVATE);
        }
    }
}
