<Project>
	<PropertyGroup>
		<BaseOutputPath>$(MSBuildThisFileDirectory)bin\</BaseOutputPath>
		<LangVersion>12.0</LangVersion>
		<TreatWarningsAsErrors>True</TreatWarningsAsErrors>
		<Deterministic>true</Deterministic>
		<GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
		<GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
		<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Debug'">
		<DefineConstants>$(DefineConstants);DEBUG;TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<DefineConstants>$(DefineConstants);TRACE</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net30'">
		<DefineConstants>$(DefineConstants);NET30</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)' == 'net45'">
		<DefineConstants>$(DefineConstants);NET45</DefineConstants>
	</PropertyGroup>

	<PropertyGroup Condition="'$(InstallerBuild)' == 'true'">
		<DefineConstants>$(DefineConstants);INSTALLER</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SonarAnalyzer.CSharp" Version="10.27.0.140913">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>
